### ISSUE TITLE
Investigate Chrome Packaged App port

### ISSUE THREAD

**Issue by devgeeks** [devgeeks/Encryptr#113]
There is a clipboard api via `document.execCommand('copy',...)`

**Comment by LostCrew** [comment]
Hi @devgeeks 

I am frankly not very accustomed to Google Chrome platforms and APIs. What is the reason to mark this attempt as `wontfix`? Moreover, is there possibility to fetch/save Encryptr entries directly from Google Chrome's clipboard?

Cheers.

**Comment by CodeGnome** [comment]
I just discovered Encryptr today, but it doesn't run on Chromebooks. I saw this issue, and didn't understand the closure reason, or indeed whether it was even possible to have this packaged as a standalone Chrome application (as opposed to a browser extension). Is there a reason this can't or won't be supported on ChromeOS or the Chrome platform? I'd be happy to open a new feature request if this issue was closed for some other reason, but Chrome support is still somehow an option.
